const TakeActionTypes = {

    INCREMENT: "INCREMENT",
    INCREMENT_TAKE: "INCREMENT_TAKE",
    INCREMENT_TAKEEVERY: "INCREMENT_TAKEEVERY",
    INCREMENT_TAKELATEST: "INCREMENT_TAKELATEST",
    DECREMENT: "DECREMENT",
    RESET: "RESET",

    INCREMENT_FROM_SAGA: 'INCREMENT_FROM_SAGA',

    SET_TAKE: "SET_TAKE",
    SET_TAKEEVERY: "SET_TAKEEVERY",
    SET_TAKELATEST: "SET_TAKELATEST"
    
}

export default TakeActionTypes;