const UserActionTypes = {

    FETCH_ORDERS_START : "FETCH_ORDERS_START",
    FETCH_ORDERS_SUCCESS : "FETCH_ORDERS_SUCCESS",
    FETCH_ORDERS_FAILURE : "FETCH_ORDERS_FAILURE", 
    USER_SIGN_OUT : "USER_SIGN_OUT",
    USER_SIGN_IN : "USER_SIGN_IN" 
}

export default UserActionTypes;
